### ISSUE TITLE
option summary still needs two files

### ISSUE THREAD

**Issue by gk7279** [ewels/ngi_visualizations#5]
Hi Phil (@ewels)

Thank you for beautiful tools.

I have sample data like this

```
ENSEMBL_ID	Gene_ID	S1_FPKM	S2_FPKM
ENSMUSG00000102693.1	4933401J01Rik	0.0	0.0
ENSMUSG00000051951.5	Xkr4	0.0	0.0
ENSMUSG00000102851.1	Gm18956	0.0	0.0
ENSMUSG00000103377.1	Gm37180	0.0	0.0
ENSMUSG00000104017.1	Gm37363	0.0	0.0
ENSMUSG00000103025.1	Gm37686	0.0	0.0
ENSMUSG00000089699.1	Gm1992	0.0	0.0
ENSMUSG00000103201.1	Gm37329	0.0	0.0
ENSMUSG00000103147.1	Gm7341	0.0	0.0
ENSMUSG00000103161.1	Gm38148	0.0	0.0
ENSMUSG00000102331.1	Gm19938	0.032177856615	0.0
ENSMUSG00000102348.1	Gm10568	0.0	0.0
ENSMUSG00000102592.1	Gm38385	0.0	0.0
ENSMUSG00000102343.1	Gm37381	0.0	0.0
ENSMUSG00000025900.12	Rp1	0.0374801066295	0.0406925401821
ENSMUSG00000102948.1	Gm6101	0.0	0.0
ENSMUSG00000104123.1	Gm37483	0.0141331044081	0.0
ENSMUSG00000025902.13	Sox17	0.0395561069729	0.0
ENSMUSG00000104238.1	Gm37587	0.0	0.0
ENSMUSG00000102269.1	Gm7357	0.0	0.0
ENSMUSG00000103003.1	Gm38076	0.0	0.0
ENSMUSG00000104328.1	Gm37323	0.0	0.0
ENSMUSG00000102735.1	Gm7369	0.179260914031	0.0892033230382
ENSMUSG00000098104.1	Gm6085	0.0142677054025	0.170396551763
ENSMUSG00000102175.1	Gm6119	0.0695639367882	0.138464859641
ENSMUSG00000103265.1	Gm2053	0.0	0.0
ENSMUSG00000103922.1	Gm6123	0.0196197632756	0.0
ENSMUSG00000033845.13	Mrpl15	0.97861631541	0.413192062599
ENSMUSG00000102275.1	Gm37144	0.182378495145	0.290414992569
ENSMUSG00000025903.14	Lypla1	4.58805075014	2.3605109438
ENSMUSG00000104217.1	Gm37988	17.2110033206	11.1325747152
ENSMUSG00000033813.15	Tcea1	10.2677823311	4.98143051557
ENSMUSG00000062588.4	Gm6104	0.0	0.0
ENSMUSG00000103280.1	Gm37277	0.0377561241074	0.0
ENSMUSG00000002459.17	Rgs20	0.0	0.0
ENSMUSG00000091305.1	Gm17100	0.0	0.0
ENSMUSG00000102653.1	Gm37079	0.0	0.0
ENSMUSG00000085623.1	Gm16041	0.0	0.0
ENSMUSG00000091665.1	Gm17101	0.0	0.0
ENSMUSG00000033793.12	Atp6v1h	1.17499955983	0.471186853068
ENSMUSG00000104352.1	Gm7182	0.0	0.0
ENSMUSG00000104046.1	Gm37567	0.0	0.0
ENSMUSG00000102907.1	Gm38264	0.0	0.0
ENSMUSG00000025905.13	Oprk1	0.0	0.0
ENSMUSG00000103936.1	Gm36965	0.0	0.0
ENSMUSG00000103519.1	Gm37429	0.0	0.0
ENSMUSG00000033774.4	Npbwr1	0.0	0.0
ENSMUSG00000103090.1	Gm19214	0.0	0.0
ENSMUSG00000025907.14	Rb1cc1	3.41373062746	1.36410037354
```

When I run this using

```
python fpkm_scatter.py -s -a -v 1.txt
```

It returns an error asking for two files. So, I specify `1.txt` two times in the above command and I get this error

```python
Traceback (most recent call last):
  File "/home/build/lib/ngi_visualizations/fpkm_scatter/fpkm_scatter.py", line 426, in <module>
    make_fpkm_scatter_plots(**kwargs)
  File "/home/build/lib/ngi_visualizations/fpkm_scatter/fpkm_scatter.py", line 82, in make_fpkm_scatter_plots
    cond_1_proj = pname_re.search(condition_1.keys()[0]).group(0)
AttributeError: 'NoneType' object has no attribute 'group'
```

Please share any valuable pointers. Thanks.

**Comment by ewels** [comment]
Hi @gk7279,

The reason it fails is because this script was designed very specifically for plotting samples from the NGI, which have consistent sample identifiers (`Pxxx_xxx` where `x` is a number). But even replacing your sample names with names that work, the script still fails later because of a different reason for me (your data is very sparse).

This script was really only developed for a one-off use at SciLifeLab and although we try to make everything we do open-source, this one was never refined for general use. I'm afraid I don't really have time to work on it now to make it polished.

I'd recommend either using a different tool (eg. this kind of thing is typically done in R, there are a lot of tutorials around for this), or if you really would like a command line Python tool like this then of course feel free to fork the code and shape it to whatever you need.

Good luck, and shout if I can be of any further help!

Phil
